# Generated by Django 4.2.11 on 2024-04-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_item_discount_item_retailer_item_return_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("clothing", "Clothing"),
                    ("electronics", "Electronics"),
                    ("books", "Books"),
                    ("hone", "Home"),
                    ("sport", "Sporting goods"),
                    ("art", "Collections & arts"),
                    ("motor", "Motors"),
                    ("bussiness", "Bussiness & Industrial"),
                ],
                default="general",
                max_length=100,
            ),
        ),
    ]
