# Generated by Django 4.2.11 on 2024-04-17 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_order_start_date_orderitem_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
    ]
